### ISSUE TITLE
error messages:  root - INFO - Missing required property: 'Service' and 'CfnBotoInterface' object has no attribute 'physical_resource_id

### ISSUE THREAD

**Issue by reidca** [dejonghe/cfn-boto-interface#3]
I thought I would give this a try on something simple to see whether it works for my use case.

I have a cloud formation template that creates IAM Roles. Sometime AWS announced that they now support longer session durations on IAM roles but alas, no cloudformation support (as usual).

So, I thought I could use this to update the role that is created by cloudformation to increase the session duration. To test I took out one of the roles that we create in the template and added the custom resource as per the docs you provided.

This is what the simple template looks like:

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  AdministratorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StaffRole_Administrator2
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::accountid:root
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  AdministratorRoleSessionDurationUpdater:
    Type: Custom::UpdateRole
    Properties:
      ServiceToken: arn:aws:lambda:eu-west-1:accountid:function:cfn-boto-interface
      Create:
        PhysicalResourceId: !Ref AdministratorRole
        Commands:
          - Client: iam
            Method: update_role
            Arguments: 
              RoleName: !Ref AdministratorRole
              MaxSessionDuration: 28800
      Update:
        Replace: 'True'
```

The Cloudformation times out and in CloudWatch I can see the following errors:

```
START RequestId: b5ac01d1-4183-11e8-a99b-ed2720da7b5a Version: $LATEST
[INFO]	2018-04-16T14:37:38.7Z	b5ac01d1-4183-11e8-a99b-ed2720da7b5a	Action: Create
[INFO]	2018-04-16T14:37:38.8Z	b5ac01d1-4183-11e8-a99b-ed2720da7b5a	Missing required property: 'Service'
'CfnBotoInterface' object has no attribute 'physical_resource_id': AttributeError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 198, in lambda_handler
boto_proxy = CfnBotoInterface(event,context)
File "/var/task/lambda_function.py", line 55, in __init__
self.set_attributes_from_event(event)
File "/var/task/lambda_function.py", line 83, in set_attributes_from_event
self.send_status(FAILED)
File "/var/task/lambda_function.py", line 182, in send_status
if self.physical_resource_id:
AttributeError: 'CfnBotoInterface' object has no attribute 'physical_resource_id'

END RequestId: b5ac01d1-4183-11e8-a99b-ed2720da7b5a
REPORT RequestId: b5ac01d1-4183-11e8-a99b-ed2720da7b5a	Duration: 1.47 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 35 MB	
2018-04-16 14:37:38,007 - root - INFO - Action: Create
2018-04-16 14:37:38,008 - root - INFO - Missing required property: 'Service'
START RequestId: b5ac01d1-4183-11e8-a99b-ed2720da7b5a Version: $LATEST
[INFO]	2018-04-16T14:38:36.173Z	b5ac01d1-4183-11e8-a99b-ed2720da7b5a	Action: Create
2018-04-16 14:38:36,173 - root - INFO - Action: Create
[INFO]	2018-04-16T14:38:36.173Z	b5ac01d1-4183-11e8-a99b-ed2720da7b5a	Missing required property: 'Service'
2018-04-16 14:38:36,173 - root - INFO - Missing required property: 'Service'
'CfnBotoInterface' object has no attribute 'physical_resource_id': AttributeError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 198, in lambda_handler
boto_proxy = CfnBotoInterface(event,context)
File "/var/task/lambda_function.py", line 55, in __init__
self.set_attributes_from_event(event)
File "/var/task/lambda_function.py", line 83, in set_attributes_from_event
self.send_status(FAILED)
File "/var/task/lambda_function.py", line 182, in send_status
if self.physical_resource_id:
AttributeError: 'CfnBotoInterface' object has no attribute 'physical_resource_id'

END RequestId: b5ac01d1-4183-11e8-a99b-ed2720da7b5a
REPORT RequestId: b5ac01d1-4183-11e8-a99b-ed2720da7b5a	Duration: 10.18 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 35 MB	

```

What am I missing?

**Comment by dejonghe** [comment]
Hey there, 

This is totally my mistake. I updated the code, wrote the blog and README but did not update the built release. I've just updated the 0.1.0 release package after testing the secret manager example. Please pull down the new zip file and give this another try. 

If you have issues still I'm happy to help figure it out, if it works just let me know and we can close this issue. From the looks of your cfn sample what you have should work granted that these are all the args you need for update role.

**Comment by dejonghe** [comment]
I tested with your example it fails because CFN translates everything to string and this call needs int.
Going to enable modifiers to be used everywhere.

**Comment by reidca** [comment]
Thanks, no matter how much testing you do there is always someone with a use case you have not thought of!

You probably should mention as well that the IAM role that the function assumes will need permissions to do pretty much everything. This may help someone in the future.

**Comment by reidca** [comment]
Also, the release still shows as version 1 but it also says this was added 4 days ago?

**Comment by dejonghe** [comment]
Yeah I just updated the package that's there because that one, while it worked there are no docs to support it. 

This whole thing about having to convert string int datetime... i knew it was going to be a pain. I've got a new release testing for pre template modifiers. Should be just pushed up in 30-60 min.

**Comment by dejonghe** [comment]
https://github.com/dejonghe/cfn-boto-interface/releases/tag/0.2.0

This tested and worked with your test case.

**Comment by dejonghe** [comment]
Hey forgot to mention your custom resource needs to be updated to call a modifier to set your timeout in seconds to an Int()
```  AdministratorRoleSessionDurationUpdater:
    Type: Custom::UpdateRole
    Properties:
      ServiceToken: !GetAtt 'BotoInterface.Arn'
      Create:
        PhysicalResourceId: !Ref 'AdministratorRole'
        Commands:
          - Client: iam
            Method: update_role
            Arguments:
              RoleName: !Ref 'AdministratorRole'
              MaxSessionDuration: '!int.28800'
      Update:
        Replace: 'True'
```

**Comment by reidca** [comment]
Testing working perfectly now, thank you. Great resource.
